services:
  - type: web
    plan: free
    name: smart-academy
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m daphne -b 0.0.0.0 -p $PORT ssbi.asgi:application"
  
    envVars:
    - key: DJANGO_SETTINGS_MODULE
      value: ssbi.settings
    