# Generated by Django 5.1.3 on 2025-01-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('question_number', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField()),
                ('hr_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('min_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=600)),
                ('quiz_title', models.TextField(blank=True, max_length=50000, null=True)),
                ('answer', models.TextField(blank=True, max_length=50000, null=True)),
                ('quiz_answer', models.TextField(blank=True, max_length=5000, null=True)),
                ('raw_answer', models.JSONField(blank=True, max_length=50000, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.CharField(blank=True, max_length=200, null=True)),
                ('entry_type', models.CharField(blank=True, choices=[('quiz', '0'), ('lesson', '1')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('questions', models.ManyToManyField(related_name='questionaires', to='main.question')),
            ],
        ),
    ]
