# Generated by Django 5.1.3 on 2025-06-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('question', 'question'), ('lesson', 'lesson')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('question', 'question'), ('lesson', 'lesson')], max_length=200, null=True),
        ),
    ]
