# Generated by Django 5.1.3 on 2025-10-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_questionnaire_id_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz_title',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, max_length=999999, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
